"""Handlers del bot y ConversationHandler."""
from telegram.ext import CommandHandler, ConversationHandler, MessageHandler

from src.config import (
    CREAR_CUENTA_NOMBRE,
    CREAR_CUENTA_TIPO,
    GASTO_CUENTA,
    GASTO_MONTO,
    GASTO_CATEGORIA,
    INGRESO_CUENTA,
    INGRESO_MONTO,
    INGRESO_CATEGORIA,
    TRANSFERENCIA_ORIGEN,
    TRANSFERENCIA_DESTINO,
    TRANSFERENCIA_MONTO,
    REGISTROS_CUENTA,
    EDITAR_ID,
    EDITAR_MONTO,
    EDITAR_CATEGORIA,
    ELIMINAR_ID,
    RESUMEN_CAT_MES,
    RESUMEN_CAT_ANO,
    RESUMEN_MES_ANO,
    RESUMEN_MES_MES,
    TEXT,
)
from src.handlers import commands, cuentas, movimientos, historial, resumenes

conv_handler = ConversationHandler(
    entry_points=[
        CommandHandler("crear_cuenta", cuentas.crear_cuenta_start),
        CommandHandler("gasto", movimientos.gasto_start),
        CommandHandler("ingreso", movimientos.ingreso_start),
        CommandHandler("transferencia", movimientos.transferencia_start),
        CommandHandler("registros", historial.registros_start),
        CommandHandler("editar", historial.editar_start),
        CommandHandler("eliminar", historial.eliminar_start),
        CommandHandler("resumen_categorias", resumenes.resumen_cat_start),
        CommandHandler("resumen_mes", resumenes.resumen_mes_start),
    ],
    states={
        CREAR_CUENTA_NOMBRE: [MessageHandler(TEXT, cuentas.crear_cuenta_nombre)],
        CREAR_CUENTA_TIPO: [MessageHandler(TEXT, cuentas.crear_cuenta_tipo)],
        GASTO_CUENTA: [MessageHandler(TEXT, movimientos.gasto_cuenta)],
        GASTO_MONTO: [MessageHandler(TEXT, movimientos.gasto_monto)],
        GASTO_CATEGORIA: [MessageHandler(TEXT, movimientos.gasto_categoria)],
        INGRESO_CUENTA: [MessageHandler(TEXT, movimientos.ingreso_cuenta)],
        INGRESO_MONTO: [MessageHandler(TEXT, movimientos.ingreso_monto)],
        INGRESO_CATEGORIA: [MessageHandler(TEXT, movimientos.ingreso_categoria)],
        TRANSFERENCIA_ORIGEN: [MessageHandler(TEXT, movimientos.transferencia_origen)],
        TRANSFERENCIA_DESTINO: [MessageHandler(TEXT, movimientos.transferencia_destino)],
        TRANSFERENCIA_MONTO: [MessageHandler(TEXT, movimientos.transferencia_monto)],
        REGISTROS_CUENTA: [MessageHandler(TEXT, historial.registros_cuenta)],
        EDITAR_ID: [MessageHandler(TEXT, historial.editar_id)],
        EDITAR_MONTO: [MessageHandler(TEXT, historial.editar_monto)],
        EDITAR_CATEGORIA: [MessageHandler(TEXT, historial.editar_categoria)],
        ELIMINAR_ID: [MessageHandler(TEXT, historial.eliminar_id)],
        RESUMEN_CAT_MES: [MessageHandler(TEXT, resumenes.resumen_cat_mes)],
        RESUMEN_CAT_ANO: [MessageHandler(TEXT, resumenes.resumen_cat_ano)],
        RESUMEN_MES_ANO: [MessageHandler(TEXT, resumenes.resumen_mes_ano)],
        RESUMEN_MES_MES: [MessageHandler(TEXT, resumenes.resumen_mes_mes)],
    },
    fallbacks=[
        CommandHandler("cancel", commands.cmd_cancel),
        CommandHandler("crear_cuenta", cuentas.crear_cuenta_start),
        CommandHandler("gasto", movimientos.gasto_start),
        CommandHandler("ingreso", movimientos.ingreso_start),
        CommandHandler("transferencia", movimientos.transferencia_start),
        CommandHandler("registros", historial.registros_start),
        CommandHandler("editar", historial.editar_start),
        CommandHandler("eliminar", historial.eliminar_start),
        CommandHandler("resumen_categorias", resumenes.resumen_cat_start),
        CommandHandler("resumen_mes", resumenes.resumen_mes_start),
    ],
)
